#!/usr/bin/env python3

import sys
import re

# Regex tester: regex101.com

class LineInfo:
    def __init__(self, label = None):
        self._label = label

    def __str__(self):
        return "Label = " + str(self._label)

def parseInstruction(line):

    label = None

    line = line.rstrip()

    line = line[:40]

    match = re.match(r'\s*(?P<label>[A-Z]+):', line, re.IGNORECASE)

    if match:
#        print(match.group(1))
        label = match.group("label")

        line = line[match.end("label") + 2:]
#        print(label)
#        print("It matched!")

    print(line)

    info = LineInfo(label)

    return info

def pass1(fileStream):
    lines = []
    symbolTable = {}
    loc = 0
    for line in fileStream:
        info = parseInstruction(line)

        lines.append(info)
#        print(info)
        if info._label:
            symbolTable[info._label] = loc

    print(symbolTable)

    return lines, symbolTable

def pass2(lines, symbolTable):
    pass

def main():
    lines, symbolTable = pass1(sys.stdin)
    pass2(lines, symbolTable)


if __name__ == "__main__":
   main()
